version: '3.7'
services:
  gamification_db:
    image: mysql
    container_name: gamification_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amt_gamification
      MYSQL_USER: gamification_user
      MYSQL_PASSWORD: gamification_secret
    ports:
      - "3308:3306"
    expose:
      - '3308'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  gamification_server:
    image: amt/gamification
    container_name: gamification_server
    environment:
      - MYSQL_HOST=gamification_db
    depends_on:
      - gamification_db
    ports:
      - "8090:8090"
      - "8444:8443"
    expose:
      - '8090'

