name: build and publish Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

    #  - name: change environnment
    #  run: echo "MYSQL_HOST=db_gamification" > badges-impl/.env

      - name: build image
        run: |
          chmod +x ./build-image.sh
          ./build-image.sh

      - name: run compose
        run: |
          cd docker/topologies/dev
          docker-compose up -d

      - name: run cucumber tests
        run: |
          cd badges-specs
          mvn clean test
          #  - name: Run cucumber tests
          #  run: |
          # chmod +x start-db.sh
          # ./start-db.sh
          # cd badges-impl
          # mvn clean compile spring-boot:start
          # curl http://localhost:8080
          # cd ../badges-specs
          # mvn clean test

      - name: Build and publish Docker image
        run: echo ${{ secrets.PAT_RMGG_DEPLOY }} | docker login ghcr.io -u RMGG-deploy --password-stdin &&
          docker tag amt/gamification ghcr.io/amt-rmgg/amt-gamification &&
          docker push ghcr.io/amt-rmgg/amt-gamification
